title: VuDucHong Official Blog
description: > # this means to ignore newlines until "baseurl:"
  Chia sẻ về cuộc sống, công việc, những suy nghĩ của cá nhân về mọi thứ trong xã hội. Chia sẻ kiến thức lập trình, đồ họa, thủ thuật internet và nhiều thứ khác
permalink: ':title/'
baseurl: "http://tinhyeucongnghe.net" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vu Duc Hong # add your name
author-img: avatar.jpg # add your photo
about-author: Tôi là một lập trình viên, yêu thích công nghệ, viết bài và chia sẻ. # add description
social-twitter: vuduchong209305 # add your Twitter handle
social-facebook: vuduchongdotcom # add your Facebook handle
social-github: vuduchong209305 # add your Github handle
social-linkedin: vu-duc-hong-ab8748149 # add your Linkedin handle
social-email: vuduchong209305@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
